---
title: "Notes from myself I"
author: "Drew Tyre"
date: '`r Sys.Date()`'
output: 
  html_document:
    code_folding: hide
draft: yes
slug: dispatches-1
tags_include:
- Mental Health
- Counseling
categories: Personal
---

A couple months ago I realized that my low, but stable, state was in fact a nosedive.
Since then I pretty much cratered, crawled out, and maybe, just maybe, I'm back
on my feet again. Trigger warning: I will discuss suicidal ideation below.

I spent the week following my realization just waiting for something new to happen.
I refocused on a very small number of things that just had to get done. Each day, 
one thing. I've been very, very lucky to have the support of my boss. As a result of
that I've started handing off the organizing of the Ecology Lab for the fall. This
had to happen eventually, but my relapse into depression accelerated the pace a great deal. 

I also met with a friend to just ramble aimlessly for a bit. Just empathetic listening,
not trying to solve my problem, which at that point seemed insoluble. 

> I'm already out
> of foolproof ideas, so don't ask me how
> To get started, it's all uncharted
> -- Sara Bareilles, Uncharted

I love that song, and that line captures a lot of how I felt. Still, having 
someone sit with me and just listen, magic. 

I started Transcranial Magnetic Stimulation, which is a refinement of
Electro-Convulsive Therapy. Basically, it stimulates the neurons in a specific 
brain region without the "Convulsive" part. TMS is well documented to help a large fraction 
of people with treatment resistant depression, although not everybody responds.
Daily treatments for about 6 weeks are required, and even after that, if it works,
"tune ups" are required every so often. But a friend tried it earlier this year,
and when I last spoke with them they were taking no medication at all. 

2 seconds of magnetic pulses every 20 
seconds for 20 minutes, targeting the left dorso-lateral precortex. It isn't very comfortable, and initially I left the sessions with
a headache. Most of the time I just breathe, eyes closed, counting breaths. It is
hard to have a conversation with the tech when every 18 seconds a woodpecker starts
hammering on your skull. The muscles in the right side of my jaw clench. Then it 
passes and I resume counting. 
The first day or two I felt pretty wide awake right afterward, although
the feeling didn't last past noon.

Wednesday of the week I started TMS I hit the bottom of this cycle. I lay awake most of the night thinking
of suicide. Suicidal ideation (SI) isn't new to me, but normally I'm able to separate
the occurence of those thoughts from me, myself. The thought appears, flashes past,
and goes away. Now, that's still not good, but as a friend says it is like background radiation:
there, but not particularly harmful. Wednesday evening the SI went from background 
radiation to full-blown thinking. So that wasn't fun.

By the end of that first week I was also experiencing a high level of free-floating anxiety.
I don't normally experience this; my anxiety is episodic, usually clearly attached
to something like an upcoming deadline. Free-floating anxiety is just there, and
ugh, I don't want to feel like that ever again! My friend who also did TMS experienced the
same spike in anxiety. At the start of the 2nd week of
TMS, my psychiatrist added a "right side" treatment to inhibit the anxiety. This 
is a magnetic pulse every second for ~ 3 minutes, targeting the right dorsolateral prefrontal cortex. 
And, um, wow! It just worked. No anxiety. This stuff is amazing.

Over the next few weeks my mood drifted steadily upwards, although I still 
struggled to concentrate and focus on work. I felt well enough to try a lower dose
of one medication, Mirtazipine. That stuff turns me into a zombie at 15 mg a day,
but at 7.5 I wasn't getting my symptoms under control. So I'd been taking 11.75 mg
a day since May or so, which controlled my symptoms and didn't completely knock 
me out. Although I slept, I never
felt rested while taking the Mirtazipine. When I dropped the dose down to 7.5 mg 
again, it felt like coming out from under a cloud. Suddenly I was sleeping better,
waking rested, and just ... felt good. By the end of the 4th week of TMS, with the
lowered dose of Mirtazipine, I felt better than I had imagined was possible. 

I still wasn't able to concentrate though. Drifting along in a happy mood was fine,
but I want to be able to work too! At the start of the 5th week of TMS, my psychiatrist
shifted the inhibitory right side treatment to the stimulating fast pulse trains.
I was worried the anxiety would come back, but it didn't. I think my concentration
and focus improved, but those things are harder to track, and I'm dealing with some other
personal issues that also occupied a huge amount of the past couple weeks.

Today I am one week out from my last TMS treatment, and I feel OK. I'm not great,
but the stuff I'm dealing with can knock a healthy person into a depressed state,
so I think I'm doing very well, considering! I'm excited about the future again,
cooking is a pleasure, and I'm even starting to work again. Over the coming weeks
I will continue to return for follow-up appointments with the psychiatrist to 
keep evaluating my mental state. I'm keeping my fingers crossed that this treatment
sticks. 







