---
title: "The unreasonable power of dominant thoughts"
author: "Drew Tyre"
date: '2019-03-25'
output: html_document
draft: yes
slug: dominant-thoughts
tags_include:
- Mental Health
- Counseling
categories: Personal
---

Today is one of those post-counselling days where my sense of self is shattered. 
Doesn't sound good, but I discovered something that needed shattering.

> Our life always expresses the result of our dominant thoughts. - Soren Kierkegaard

My councilor and I were discussing this quote today. Figuring out my "dominant 
thoughts" is harder than it seems. They're not common surface thoughts that can 
be mindfully discarded. The dominant thoughts are the deep framework that generates 
all else. Pete's suggestion was to think about what my life was expressing,
and work backwards from that. 

This past week was hard. I reviewed my mid-semester course evaluations. A colleague 
generously took the time to watch my class, and noticed many students struggling.
Administrative tasks were piling up. At home, I struggled to make time to exercise.
I ate too much. I drank too much alcohol. I wasn't in a high energy state to 
begin the week, and day by day my energy evaporated, my 
motivation dried up. Yesterday,
dragging myself through preparing for work, I thought "I just wish this was all
over". And bang, just like that I was back in the dark place I'd barely
crawled out of a few weeks ago. I promptly crawled back out again, but it was a stark 
reminder of what's waiting just off to the side. 

Spilling all this stuff out in the open is the great thing about counciling. As I
reflected back on it all, I realized that I regarded all of it as failure. Failing
at self-control. Failing at teaching. Failing at administrating. Once I made that
observation, the revelations kept coming. I look at everything as a failure. Failing
as a friend, son, nephew, husband, father, advisor. Every project I've ever been 
responsible for, I regard as failed. 

I don't treat anyone else like this. I praise people for their efforts, remind them
that the perfect is the enemy of the good, just call it done! 

