---
title: "What is the functional response of a recreational hunter?"
author: "Drew Tyre"
date: '2019-04-12'
output: html_document
draft: yes
slug: hunter-functional-response
tags_include:
- ecology
- management
- modeling
categories: Research
---

A few years ago I built a white-tailed deer population model to evaluate different
harvest strategies. 2 sexes, density dependence, age structure, it was fun. The
main problem I came across was figuring out how changes in population
size and structure would interact with management to change harvest mortality. 
In consumer-resource modeling terminology, I didn't know what the functional 
response of hunters was. So here's my first shot at it.

To keep things simple, I will just think about 2 types of deer, does ($N_d$) 
and bucks ($N_b$). Furthermore, hunters always prefer bucks. In practice this
means if they encounter a buck they harvest it. The real trick is figuring out
what they do when they encounter a doe. Simplifying again, each permit only 
allows 1 deer, so if they take a doe then that precludes taking a buck. 
Each hunter has some limited time in which to harvest any animal (limited season). 
Simplifying, assume that's the same for all hunters. Finally, hunters encounter 
deer at rates proportional to their abundance $\lambda(N)$. This rate depends 
on deer behavior, hunter behavior, and the habitat involved.

If hunters have discrete intervals in which to encounter a deer, then this is kind
of like a negative binomial distribution -- how many non-bucks are encountered
before encountering a buck. The problem is we have two kinds of events, not one.
For a single interval

$$
p(buck | N) = 1-e^{\lambda N_b} \\
p(doe | N) = (1-e^{\lambda N_d})(1-p(buck)) \\
p(nothing) = (1 - p(buck))(1-p(doe))
$$

Here I assume that if a doe and a buck are encountered, the hunter always takes
the buck and ignores the doe. Also, if more than one buck or doe is encountered
that's the same as encountering one.

So this is a dynamic programming problem -- there are T intervals, and on each
interval the decision is to take a doe or not. 

$$
V(t) = max(p(buck) + v_d p(doe) + V(t+1) p(nothing), \\
           p(buck) + V(t+1)(p(doe) + p(nothing)))
$$

where $0 \leq v_d \leq 1$ is the relative value of a doe compared to a buck.

```{r, echo = FALSE}
library("tidyverse")
lambda <-  0.01
N <-  c(doe = 100, buck = 2)
vd <-  0.1
p_enc <- function(N, lambda){
  c(pbuck = 1 - exp(-lambda*N[2]),
    pdoe = (1 - exp(-lambda*N[1]))*(exp(-lambda*N[2])),
    pnone = (exp(-lambda*N[1]))*(exp(-lambda*N[2])))
    }
V <- vector("numeric", length = 20)
V1 <- vector("numeric", length = 20)
V2 <- vector("numeric", length = 20)
D <- vector("character", length = 20)
p <- p_enc(N, lambda)
V[20] <- V1[20] <- V2[20] <- p[2] + vd*p[1]
D[20] <- "accept"

for(t in 19:1){
  V1[t] <- p[2] + vd*p[1] + p[3]*V[t+1]
  V2[t] <- p[2] + V[t+1]*(p[1] + p[3])
  if (V1[t] > V2[t]){
    D[t] <- "accept"
    V[t] <- V1[t]
  } else {
    D[t] <- "reject"
    V[t] <- V2[t]
  }
}
df <- bind_cols(t = 1:20, V = V, D = D, Accept = V1, Reject = V2) %>% 
  gather(key = Choice, value = Value, 4:5)
ggplot(data = df,
       mapping = aes(x = t)) +
  geom_line(mapping = aes(y = Value, linetype = Choice)) + 
  labs(x = "Time", y = "Value", 
       caption = "Expected value of rejecting (solid line) or accepting (dashed line) a doe.")
```

So that was unexpected, but clear once I look at the equation again. As long as
$v_d > 0$, accepting will always 