---
title: "Applying Ostrom's design principles to fish and wildlife management"
author: "Drew Tyre"
date: '`r Sys.Date()`'
output: 
  html_document:
    code_folding: hide
draft: yes
slug: managing-the-commons
tags_include:
- ecology
- management
categories: Research
---

Elinor Ostrom won a nobel prize in economics for
describing the conditions under which groups exploiting natural resources can self govern without
top-down regulation. She formulated [8 design principles to follow](https://www.ecologyandsociety.org/vol15/iss4/art38/). 
What do those look
like in the context of fish and wildlife management in the United States?

## Clearly defined boundaries

Boundaries refer not only to spatial boundaries, but also to who is in the 
group and who is out of the group. Wildlife management in the USA usually 
has clear spatial boundaries. Who is in the group is not as clearly defined.
On the one hand, the group of people who purchase licenses or permits to
harvest wildlife seems clear enough. But even membership in that group
fluctuates rapidly from year to year. I bought a Nebraska fishing license in 
2017, but not in 2018 or 2019 (yet!). Furthermore, under the public trust doctrine all
the taxpayers of a state collectively "own" the fish and wildlife living 
in the state. For many large and charismatic 
species (e.g. mountain lions), groups outside of a state may express strong
opinions about management. However, a large proportion of those "with standing"
are completely unaware or disengaged with wildlife management.


## Proportional equivalence between benefits and costs

The idea behind this principle is that obtaining benefits carries some cost. 
For consumptive users of fish and wildlife this is true. Excise taxes on firearms, 
ammunition, and fishing equipment support fish and wildlife management directly. 
In addition, a license or permit must be purchased, which varies in
cost according to the magnitude of the benefit. 

However, there is little cost to non-consumptive users for extracting their
benefits, which include viewing opportunities and existence value of game species. 
From the perspective of consumptive users, these benefits are appropriated and
not fairly obtained. 

Non-game species benefit indirectly from management funded by consumptive use
of game species. In the USA, [taxpayers broadly fund the State Wildlife Grants program](https://digitalcommons.unl.edu/cgi/viewcontent.cgi?article=1080&context=ncfwrustaff) that supports
non-game species management, and the [land and water conservation fund](https://www.doi.gov/lwcf)
that funds both game and non-game habitat management and restoration. 
Nonetheless, I value viewing opportunities for
game species as well, and that is a benefit that I have not directly paid for.

There is another, diffuse, group of stakeholders that either pay or perceive that they
pay a cost for the presence of large predators. Ranchers are prominent in this group, but they
are not the only ones concerned with living alongside predators. This group
perceives little (or no) benefit to the conservation of predators, and perceives a 
large cost. No proportionality for them, either. 

There are [some ideas out there for how to improve this situation](https://www.outdoorlife.com/articles/hunting/2016/01/it-time-rethink-north-american-model-wildlife-conservation/):

* Expand the Pittman-Robertson concept to cover more than just guns, ammo, bows, and arrows. Why not optics, knives, GPS units, boots, ATVs, decoys, camping gear, and packs? 
* Consider a general sales tax appropriation for state wildlife agencies. Missouri and Arkansas are already there, and in those states, outdoor recreation (including hunting and fishing) is flourishing.

## Collective choice arrangements

This principle requires that all individuals in the group participate in making decisions. 
This is pretty clearly false for wildlife management in the USA. All individuals in the
group do vote to elect politicians at the federal and state level, but that is a pretty 
indirect degree of participation. In some states, like my home state of 
Nebraska, fish and wildlife management decisions are made by a group of commissioners
appointed by the Governor, further reducing the participation of stakeholders. 
I suppose you can communicate with them if you're interested, but they are under no
obligation to listen. 

[Not everyone agrees that fish and wildlife management should be *more* democratic in 
nature](https://www.outdoorlife.com/articles/hunting/2016/01/it-time-rethink-north-american-model-wildlife-conservation/). 

> Ever hear of a ballot initiative? Well, it's basically a work-around for zealots who can't advance their agendas via the usual lawmaking channels. - Steve Wagner

Wagner views the ballot initiative as an end-run around scientific management. 
But ballot initiatives are a response to the absence of viable collective choice arrangements.
If stakeholders can't get a ballot initiative, they might use the court system instead to
block management actions. 

## Monitoring

Compliance with the rules agreed upon by the group needs to be monitored. This is
true for fish and wildlife management to a certain degree, but it is weak. Poaching
is illegal, and states have law enforcement dedicated to enforcing fish and game 
regulations. 

## Graduated sanctions

Small violations of the rules should result in small penalties, and large violations
have large penalties. Seems simple enough, and probably true for poaching.

## Fast and fair conflict resolution

This one is clearly false for fish and wildlife management, because the primary
means of dealing with conflicts between stakeholders is the judicial system. 
State agency personnel work hard to manage conflicts. The bigger the fish, the
bigger the issue. It is true that most fish and wildlife management comes off 
without a hitch, even for game species; the big disagreements are in the past, and most other
stakeholders seem resigned to the status quo. 

Where local conflict resolution is clearly breaking down is the management of 
large predators. As grizzly, mountain lions, and wolves rebound from over hunting and
persecution, they are causing wildlife managers more and more headaches. 

Another area of conflict in the USA involves threatened species. These 
species often result in some group not being able to do something they
want. Whether it is building a new dam, highway or shopping mall, all
of these require checking to see if there are threatened species that
might suffer some negative consequences ("take"). 

None of these issues are quick to resolve. The ill-defined nature of the
group relevant to fish and wildlife management means there usually are no
public fora where discussions can take place, other than the courts. This isn't always 
the case. Sometimes a forum for these discussions is constructed by
the relevant state or federal agency. The [Missouri River Restoration 
Implementation Committee](https://www.nwo.usace.army.mil/mrrp/mrric/) ("Mr Rick") is one example. 

## Local autonomy

This principle means that the group gets to decide what rules apply to
natural resource extraction. Fish and Wildlife management suffers twice here.
First, [who is in the "group" is unclear][Clearly defined boundaries], and the vast majority are not involved in 
formulating rules (see [Collective choice arrangements][Collective choice arrangements]). Second,
state level decision makers are constrained by levels above them,
particularly with threatened and endangered species. This might not matter; 
the final principle [involves other tiers of rule-making authority][Appropriate relations with other tiers of rule-making authority].

There is autonomy at the state level with respect to game species and non-threatened
non-game species. Is this sufficiently local? Could we do better with a smaller
spatial extent? Hunters very much [prefer to hunt within a hour's drive 
of their homes](https://digitalcommons.unl.edu/cgi/viewcontent.cgi?article=1100&context=conservationsurvey), 
to the extent that they will tradeoff a short drive against many other
desirable properties of the hunting experience. This suggests that more
localized control of hunting regulations would be well received. However,
that would also come with the requirement to be able to limit the group more
stringently.

## Appropriate relations with other tiers of rule-making authority

This is also called "poly-centric governance". The relationship between
state agencies and federal agencies is an example of this. Are these 
relationships "appropriate"? I find this principle challenging to grok. 
What would an inapproprate relationship look like? Maybe the broader authority
can overrule the local authority at any time, and that wouldn't allow for
the local autonomy and collective choice arrangements. If that's the case,
then I think the state/federal fit is appropriate. Federal agencies, the USFWS 
in particular, can take over management of a species from states, but only
under particular conditions. 

For example, once a species is listed as vulnerable or endangered under the ESA,
USFWS becomes responsible for management. However, even then the USFWS involves states, 
as they have the "boots on the ground" that make management possible. State
and local governments also control a great deal of the public lands east of the
100th meridian, and without that habitat conservation of many species would
be compromised. 

The North American Waterfowl Management Plan is another example of 
polycentric governance. States have local authority over harvest 
regulations, but because the resource migrates across many states and 
provinces, sometimes across 3 countries, they also work together with
USFWS on management decision making within "flyway councils". This is
important, because a duck that breeds on state land in North Dakota or 
Manitoba may fly over Nebraska to winter in Texas. That duck could
be taken by a hunter anywhere along the route. USFWS 
also has authority over National Wildlife Refuges, which provide much 
of the habitat for waterfowl, especially east of the 100th meridian. Habitat "Joint Ventures"
provide another way for local participation in habitat restoration and
management throughout flyways.

# Conclusion

It seems like F&W management needs an intervention. While FWM has
polycentric governance, local autonomy (at the state level), compliance monitoring,
and graduated sanctions, we're failing at group identification, equivalence of costs 
and benefits, collective choice 
arrangements, and fast, fair conflict resolution. To me it appears
that the biggest missing piece is the forum for making decisions and
resolving conflicts. It should be local (does the state count as local?). It should be elected (collective choice). In fact,
it should look like [Nebraska's Natural Resource Districts](https://www.nrdnet.org/). 

[NRDs can manage/restore *habitat*](https://nebraskalegislature.gov/laws/statutes.php?statute=2-3229)
for fish and wildlife, as long as those activities are consistent with
the game and parks commission. It seems like a small step to add 
approving fish and game regulations to the purposes of NRDs. However, wildlife at least
are managed according to a hodge-podge of district boundaries that vary by species. As
far as I am aware, none of those boundaries match up with hydrological boundaries
that are the basis for forming water-focused natural resources districts. 

Another alternative in states like Nebraska would be to change the commission to
an elected body, responsible to the citizens of the state. It isn't 
entirely clear to me whether such a change would create a place for 
resolving conflicts, but it would move management further towards the
ideal of a collective choice arrangment. It would make for interesting
discussions if the commission had some members elected on a platform of advancing
non-game conservation. 
