---
title: "I'm out of spoons and it's only noon."
author: "Drew Tyre"
date: '`r Sys.Date()`'
output: 
  html_document:
    code_folding: hide
draft: no
slug: out-of-spoons
tags_include:
- Mental Health
- Counseling
categories: Personal
---

Hey that rhymes!

[Spoon theory](https://butyoudontlooksick.com/articles/written-by-christine/the-spoon-theory/)
is a metaphor for how chronic illness, mental or physical, reduces the energy
available for everyday tasks. You start the day with a certain number of spoons. 
Each thing you do costs a spoon. Maybe more. When you're out of spoons that's it,
you're done for the day. A healthy person starts with lots of spoons, and usually
ends the day with spoons to spare. 

If you're chronically ill, say with arthritis, or depression, your spoon supply
is limited. In my case, it varies day by day. In the run up to fall semester,
my supply has dropped dangerously low. I hadn't realized quite how low until
the end of a big college meeting this morning. I didn't have to do anything
except sit there and clap at the appropriate moments. Our amazing Dean stopped me on my way 
out to say thanks for the work I've been doing. I just about broke into tears 
right there in the auditorium. That was ... unexpected, to say the least. I
managed to grind out a thank you for the compliment, and held on until I made it
out to the car. 

I was done for today. Nonetheless I made it to my counseling appointment. Now I'm
in negative spoon territory. This isn't part of the original metaphor, but helps
explain why I have the strength to get through some days. I borrow spoons against
tomorrow's supply. Trouble is, borrowed spoons come with a ridiculously high interest 
rate. Eventually I wake up with negative spoons. Carry that kind of debt for too 
long and I will end up [where I was last winter break](/post/mental-health-redux). 
Unlike money, I can borrow spoons, but I can't save them. Surplus 
spoons disappear overnight[^2].

Not every activity costs spoons; I gain spoons from some things. Free writing 
like this blog post is, well, free. No spoons lost. Lying on the floor of my
office doesn't cost spoons either, but it looks a little weird. Early in the summer
I spent a lot of time programming and analyzing data. When things go well, spoons! 
Unfortunately those activities don't always go well, and then bleagh, spoon loss.[^1] 
But on average programming and analyzing data builds the spoon supply. Cooking
is another variable activity. When I'm cooking with spoons to spare, it
builds spoons. I really like cooking. But when I'm out -- cooking is a drag.

Looking over the last few weeks, I've spent a lot of days just sitting in my office
staring at the wall. Many evenings I'm flat broke in the spoon department. That's
not where I want to be, and the semester hasn't even started yet. So, back to the
psychiatrist tomorrow for a discussion about the medication mix. I'll be watching
my spoons very, very closely over the next few weeks. I'll hand them out sparingly.
In fact, I think I might put an envelope of spoons on the door of my office.
You want to talk to me, hand me a spoon. When the envelope's empty, sorry, come 
back tomorrow. Is there a way to have my e-mail autoresponse count spoons?


[^2]: Maybe it is more accurate to say that the discount rate on spoons is very
high too. I might be overthinking this metaphor.

[^1]: This is one of those things I've been working on. Controlling my expectations
so that when things don't work out, I don't spend a spoon on it. I almost always 
figure out the problem eventually. 
