---
title: "9 Mile Prairie Worksheet"
author: "Drew Tyre"
date: "`r Sys.Date()`"
type: "lab"
weight: 222041
---

```{r real_setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

## Introduction

The goal of this week's lab is to analyze the species area curve data from 9 Mile Prairie, and get more experience making figures and calculating summary statistics in R. Like all labs, I expect you to submit an R Markdown file that I can compile to html. You should assume any data files are in a subdirectory called "data". Your file should *not* echo the code used. Answer the *numbered questions* in text, referring to graphical and tabular output as needed. You may use base graphics or ggplot2, according to your preference. 

We collected species occurence data in nested quadrats in 3 different parts of the original 9 mile Prairie. Each section collected data from a portion burned in 2015, 2016 or earlier this year in 2017. Dr. Wedin's hypothesis is that the biodiversity will be the same in these three fields, even though they look very different to the eye.

Open RStudio and create a new project. I recommend creating a project for each week of class inside a folder called `NRES222` or whatever else works for you.

Download the data from the link in Canvas, saving it into a subdirectory of your project called `data`. Make sure to keep the filename exactly the same: `9mile_plants_all.csv`!

Create a new R Markdown file by clicking the button in the top left of RStudio with a `+` on it. Save this file into your project directory with a filename `yourlastname_ninemile.Rmd`. 

At the top of the file is some header information that you can leave as is for now.

On line 8 you will see a block of text with ` ``` ` on the top and bottom:
<pre><code>```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```</code></pre>
Remember that this is a "code chunk". Everything in between the ` ``` ` is treated as instructions to the computer. Everything outside the code chunk is rendered as regular text. Add a line to the code chunk to load the `tidyverse` package we installed last week. 
<pre><code>```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```</code></pre>

You can delete everything from the end of that code chunk to the bottom of the file. Click the Knit button at the top. You should get a preview of an HTML file that just has the header information in it. An html file will also appear in the file pane next to the Rmd file. 

## Bring the data in

We add another line to the setup code to read the data into an R object called a `data.frame`
<pre><code>```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
plants <- read_csv("data/9mile_plants_all.csv")
```</code></pre>

1) Using the graphs with the raw data, rank the 3 fields (2012CRP field, Entrance field, and 9MP) from most homogeneous (all student data sets similar) to most heterogeneous.  Why are some fields more variable (speculate)?

Now calculate the average number of species found in each size plot for each group.  Next, make a graph with the average numbers of species versus plot size for each grassland type.

2) Compare the average curves for the 3 fields.  Does the species area curve appear to follow a smooth relationship?  Is the shape of the curve the same for all four fields?

3) Which of the 3 fields had the highest plant diversity?

4) In which size plots do we generally gain the most new species?

5) Pick the field with the highest diversity. Visually estimate (extrapolate) how many species you would expect to find in a 100m2 plot in that field?

6) If you were surveying many grassland types and had to pick a single plot size to use for data collection, what size would you pick and why?
Ecologists often present species-area curves on log10  axes (both the X and Y axes) or transform the data by taking logs before graphing.  This generally turns the curve into a straight line (See the discussion of species-area curves in your ecology textbook).  It also allows the viewer to compare changes in diversity in small plots equally with changes in large plots.  On regular (linear) axes, the changes in big plots dwarf changes seen in small plots.
Mathematically, species-area curves can be fit with the non-linear equation
S = cAz  where S is species number, A is plot area, and c and z are constants. 
	We won’t use this equation in lab; non-linear equations such as this are much more difficult to work with.  However, if you transform the data for species number and plot area to log values, the relationship becomes linear. A line fit to the data averages across point to point irregularities to give the best description of the species area relationship in each area. The equation now has the form:
				LogS = log c + z (logA)

Copy  the average species number results for each grassland area to a second worksheet.  Add the functions to convert the data to log10 plot size.  Create two graphs using the 3 data sets versus plots size, one with the original (linear) axes, and one with log10 – transformed data.  Add linear trend lines, with the equation, for each data set.

7) Does the log10 – transformed data appear to follow a linear relationship?  Is the slope of the line similar for all 3 areas? 

8) Which of the 3 areas had the highest plant diversity?  Do the differences among the grassland types change between small and large plots?

9) Pick the grassland type with the highest diversity. Visually estimate (extrapolate) how many species you would expect to find in a 100m2 plot log10 – transformed data.

10) What are the equations of your log-transformed relationships for the 3 areas (they can be on the graph) ?

11) Do you think these relationships (the straight lines on the logS vs logA graph) would increase smoothly indefinitely?  What would happen if the study area crossed into a different ecosystem type (for example a stand of trees or a corn field)?

12) Use the equations to predict how many species each habitat would have at a scale of 1 m2? (Remember that the log of 1 =0, so your answer is the value of the intercept.  BUT, you have to transform it from a log scale back to linear, so take 10 raised to the value of the intercept to give the average number of species in a 1m2 plot).

13) Use the equations to predict how many species each habitat would have at a scale of 100m2 plot? 

You can calculate this from your equation.  Remember to raise your value of LogS to the power of 10 to transform it to number of species.  In Excel you can use the function
= power(10, ?) where ? is the number you want to transform.

Example: let’s say your equation is 

LogS = 1.0332 + 0.1642 (logA)

If A = 100, then logA = 2.

Plug that into the equation and you get LogS = 1.362.

Does that mean you expect to find 1.362 species in a 100 m2 plot? NO, the log of the number of species you predict is 1.362.  How do you get rid of the log?  Raise 10 to the number you have.  10 raised to the 1.263 is 21.9, which is the predicted number of species in a 100 m2 plot given the equation above.  We’ll use logs (base 10) and natural logs quite a bit in this course, so it pays to review them.  Mess around with excel until you figure out how to do this example.


Big discussion questions (each answer should be 200 – 400 words)
14) Why do you think the various fields we studied differ in plant diversity?  How does age of the field since planting, the number of species planted and the type of management appear to affect diversity?  You will need to look at some other resources to answer this question well; there is no single correct answer.

15) Based on the results of our study of diversity in these 3 neighboring grassland areas, what new observations would you propose for future study? We only measured a few of the possible combinations of land-use history (unplowed prairie versus replanted crop land) and management (burning vs haying) for grasslands in the Nine-Mile Prairie area.  Assuming you had enough time and money, design a bigger, long-term study of factors controlling plant diversity in prairies.
## Turn in

In Canvas, you will submit your R markdown file. Be sure your last name is the first part of the filename, and that it says "9mile" somewhere as well. Double check that it will work (necessary for full points) by clicking the "knit" button. If it produces an HTML file with all your figures and answers to the questions, you're good! 