---
title: "Fitting lines exercise"
author: "Drew Tyre"
date: "2016-08-20"
type: "lab"
weight: 803012
---

This example from Gelman and Nolan 2002 Teaching Statistics: A bag of tricks, chapter 4.

```{r, echo=FALSE, results='hide', eval=FALSE}

# fitting lines by eye, export to pdf
pdf("fittinglines.pdf")
par(mfrow=c(2,2))
x = c(1,2,3)
y = x
plot(x,y,xlab="",ylab="",bty="n",xlim=c(0,3),ylim=c(0,3))
x = c(1,1,2)
y = c(1,2,2)
plot(x,y,xlab="",ylab="",bty="n",xlim=c(0,3),ylim=c(0,3))
x = c(1,1,2,2)
y = c(1,2,1,2)
plot(x,y,xlab="",ylab="",bty="n",xlim=c(0,3),ylim=c(0,3))
x = c(1,2,3,3,4,5)
y = c(2,3,1,3,2,3)
plot(x,y,xlab="",ylab="",bty="n",xlim=c(0,6),ylim=c(0,4))
dev.off()
par(mar=c(3,3,0,0))
```

```{r, fig.height=3, fig.width=3,fig.cap="" }
# now make each figure and the corresponding r lm() output
x = c(1,2,3)
y = x
plot(x,y,xlab="",ylab="",bty="n",xlim=c(0,3),ylim=c(0,3))
lm.1 = lm(y~x)
abline(lm.1)
summary(lm.1)
```
\pagebreak

```{r, fig.height=3, fig.width=3,fig.cap=""}
# now make each figure and the corresponding r lm() output
x = c(1,1,2)
y = c(1,2,2)
plot(x,y,xlab="",ylab="",bty="n",xlim=c(0,3),ylim=c(0,3))
lm.1 = lm(y~x)
abline(lm.1)
summary(lm.1)
```
\pagebreak


```{r,fig.height=3, fig.width=3 ,fig.cap=""}
# now make each figure and the corresponding r lm() output
x = c(1,1,2,2)
y = c(1,2,1,2)
plot(x,y,xlab="",ylab="",bty="n",xlim=c(0,3),ylim=c(0,3))
lm.1 = lm(y~x)
abline(lm.1)
summary(lm.1)
```
\pagebreak

```{r, fig.height=3, fig.width=3,fig.cap=""}
# now make each figure and the corresponding r lm() output
x = c(1,2,3,3,4,5)
y = c(2,3,1,3,2,3)
plot(x,y,xlab="",ylab="",bty="n",xlim=c(0,6),ylim=c(0,4))
lm.1 = lm(y~x)
abline(lm.1)
summary(lm.1)
```


